stages:
  data_ingestion:
    cmd: python -m src.data.data_ingestion
    deps:
      - src/data/data_ingestion.py
      - params.yaml
    params:
      - data_ingestion.test_size
    outs:
      - data/raw

  data_preprocessing:
    cmd: python -m src.data.data_preprocessing
    deps:
      - src/data/data_preprocessing.py
      - data/raw
    outs:
      - data/interim

  model_building:
    cmd: python -m src.data.model_building
    deps:
      - src/data/model_building.py
      - data/interim
      - params.yaml
    params:
      - model_building.max_features
      - model_building.ngram_range
      - model_building.learning_rate
      - model_building.max_depth
      - model_building.n_estimators
    outs:
      - artifacts/lgbm_model.pkl
      - artifacts/tfidf_vectorizer.pkl

  model_evaluation:
    cmd: python -m src.data.model_evaluation
    deps:
      - src/data/model_evaluation.py
      - artifacts/lgbm_model.pkl
      - artifacts/tfidf_vectorizer.pkl
      - data/interim
    metrics:
      - artifacts/experiment_info.json:
          cache: false
